name: validate

on:
  push:
    branches: [ main ]

jobs:
  main:
    # ignore all-contributors PRs
    if: ${{ !contains(github.head_ref, 'all-contributors') }}
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Build the docker-compose stack
        run: |
          docker-compose build
          docker-compose up -d

      - name: ▶️ Run tests
        run: mvn test